---
- hosts: win10
  become_method: runas
  become_user: '{{ ansible_user }}'
  become: yes
  gather_facts: no

  tasks:
  - name: install jdk1.8.0_211
    win_chocolatey:
      name:  
        - jdk8
      state: present
  
  - name: add java to PATH
    win_path:
      elements:
        - 'C:\Program Files\Java\jdk1.8.0_211\bin'
      scope: machine
      state: present

  - name: install python3.6.5
    win_chocolatey:
      name:
        - python
      state: present
      version: 3.6.5
      
  - name: install packages
    win_chocolatey:
      name: "{{ item }}"
      state: present
      ignore_checksums: yes
    loop:
      - notepadplusplus
      - vscode
      - dotnet3.5
      - dotnetfx
      - ghidra
      - ollydbg
      - javadecompiler-gui
      - hxd
      - wireshark
      - fiddler
      - ida-free
      - hashmyfiles
      - burp-suite-free-edition
      - processhacker
      - office-tool
      - procexp
      - dependencywalker
      - exeinfo
      - regshot
      - reshack
      - dotpeek
      - ilspy
      - orwelldevcpp
      - cfr
      - eazfuscator.net
      - yara

  - name: Reboot machine
    win_reboot:

  - name: Ensure WinRM starts upon reboot
    win_service:
      name: WinRM
      start_mode: delayed



